#!/bin/bash
multichain-cli metar create stream AF false
multichain-cli metar create stream AX false
multichain-cli metar create stream AL false
multichain-cli metar create stream DZ false
multichain-cli metar create stream AS false
multichain-cli metar create stream AD false
multichain-cli metar create stream AO false
multichain-cli metar create stream AI false
multichain-cli metar create stream AQ false
multichain-cli metar create stream AG false
multichain-cli metar create stream AR false
multichain-cli metar create stream AM false
multichain-cli metar create stream AW false
multichain-cli metar create stream AU false
multichain-cli metar create stream AT false
multichain-cli metar create stream AZ false
multichain-cli metar create stream BS false
multichain-cli metar create stream BH false
multichain-cli metar create stream BD false
multichain-cli metar create stream BB false
multichain-cli metar create stream BY false
multichain-cli metar create stream BE false
multichain-cli metar create stream BZ false
multichain-cli metar create stream BJ false
multichain-cli metar create stream BM false
multichain-cli metar create stream BT false
multichain-cli metar create stream BO false
multichain-cli metar create stream BQ false
multichain-cli metar create stream BA false
multichain-cli metar create stream BW false
multichain-cli metar create stream BV false
multichain-cli metar create stream BR false
multichain-cli metar create stream IO false
multichain-cli metar create stream BN false
multichain-cli metar create stream BG false
multichain-cli metar create stream BF false
multichain-cli metar create stream BI false
multichain-cli metar create stream KH false
multichain-cli metar create stream CM false
multichain-cli metar create stream CA false
multichain-cli metar create stream CV false
multichain-cli metar create stream KY false
multichain-cli metar create stream CF false
multichain-cli metar create stream TD false
multichain-cli metar create stream CL false
multichain-cli metar create stream CN false
multichain-cli metar create stream CX false
multichain-cli metar create stream CC false
multichain-cli metar create stream CO false
multichain-cli metar create stream KM false
multichain-cli metar create stream CG false
multichain-cli metar create stream CD false
multichain-cli metar create stream CK false
multichain-cli metar create stream CR false
multichain-cli metar create stream CI false
multichain-cli metar create stream HR false
multichain-cli metar create stream CU false
multichain-cli metar create stream CW false
multichain-cli metar create stream CY false
multichain-cli metar create stream CZ false
multichain-cli metar create stream DK false
multichain-cli metar create stream DJ false
multichain-cli metar create stream DM false
multichain-cli metar create stream DO false
multichain-cli metar create stream EC false
multichain-cli metar create stream EG false
multichain-cli metar create stream SV false
multichain-cli metar create stream GQ false
multichain-cli metar create stream ER false
multichain-cli metar create stream EE false
multichain-cli metar create stream ET false
multichain-cli metar create stream FK false
multichain-cli metar create stream FO false
multichain-cli metar create stream FJ false
multichain-cli metar create stream FI false
multichain-cli metar create stream FR false
multichain-cli metar create stream GF false
multichain-cli metar create stream PF false
multichain-cli metar create stream TF false
multichain-cli metar create stream GA false
multichain-cli metar create stream GM false
multichain-cli metar create stream GE false
multichain-cli metar create stream DE false
multichain-cli metar create stream GH false
multichain-cli metar create stream GI false
multichain-cli metar create stream GR false
multichain-cli metar create stream GL false
multichain-cli metar create stream GD false
multichain-cli metar create stream GP false
multichain-cli metar create stream GU false
multichain-cli metar create stream GT false
multichain-cli metar create stream GG false
multichain-cli metar create stream GN false
multichain-cli metar create stream GW false
multichain-cli metar create stream GY false
multichain-cli metar create stream HT false
multichain-cli metar create stream HM false
multichain-cli metar create stream VA false
multichain-cli metar create stream HN false
multichain-cli metar create stream HK false
multichain-cli metar create stream HU false
multichain-cli metar create stream IS false
multichain-cli metar create stream IN false
multichain-cli metar create stream ID false
multichain-cli metar create stream IR false
multichain-cli metar create stream IQ false
multichain-cli metar create stream IE false
multichain-cli metar create stream IM false
multichain-cli metar create stream IL false
multichain-cli metar create stream IT false
multichain-cli metar create stream JM false
multichain-cli metar create stream JP false
multichain-cli metar create stream JE false
multichain-cli metar create stream JO false
multichain-cli metar create stream KZ false
multichain-cli metar create stream KE false
multichain-cli metar create stream KI false
multichain-cli metar create stream KP false
multichain-cli metar create stream KR false
multichain-cli metar create stream KW false
multichain-cli metar create stream KG false
multichain-cli metar create stream LA false
multichain-cli metar create stream LV false
multichain-cli metar create stream LB false
multichain-cli metar create stream LS false
multichain-cli metar create stream LR false
multichain-cli metar create stream LY false
multichain-cli metar create stream LI false
multichain-cli metar create stream LT false
multichain-cli metar create stream LU false
multichain-cli metar create stream MO false
multichain-cli metar create stream MK false
multichain-cli metar create stream MG false
multichain-cli metar create stream MW false
multichain-cli metar create stream MY false
multichain-cli metar create stream MV false
multichain-cli metar create stream ML false
multichain-cli metar create stream MT false
multichain-cli metar create stream MH false
multichain-cli metar create stream MQ false
multichain-cli metar create stream MR false
multichain-cli metar create stream MU false
multichain-cli metar create stream YT false
multichain-cli metar create stream MX false
multichain-cli metar create stream FM false
multichain-cli metar create stream MD false
multichain-cli metar create stream MC false
multichain-cli metar create stream MN false
multichain-cli metar create stream ME false
multichain-cli metar create stream MS false
multichain-cli metar create stream MA false
multichain-cli metar create stream MZ false
multichain-cli metar create stream MM false
multichain-cli metar create stream NA false
multichain-cli metar create stream NR false
multichain-cli metar create stream NP false
multichain-cli metar create stream NL false
multichain-cli metar create stream NC false
multichain-cli metar create stream NZ false
multichain-cli metar create stream NI false
multichain-cli metar create stream NE false
multichain-cli metar create stream NG false
multichain-cli metar create stream NU false
multichain-cli metar create stream NF false
multichain-cli metar create stream MP false
multichain-cli metar create stream NO false
multichain-cli metar create stream OM false
multichain-cli metar create stream PK false
multichain-cli metar create stream PW false
multichain-cli metar create stream PS false
multichain-cli metar create stream PA false
multichain-cli metar create stream PG false
multichain-cli metar create stream PY false
multichain-cli metar create stream PE false
multichain-cli metar create stream PH false
multichain-cli metar create stream PN false
multichain-cli metar create stream PL false
multichain-cli metar create stream PT false
multichain-cli metar create stream PR false
multichain-cli metar create stream QA false
multichain-cli metar create stream RE false
multichain-cli metar create stream RO false
multichain-cli metar create stream RU false
multichain-cli metar create stream RW false
multichain-cli metar create stream BL false
multichain-cli metar create stream SH false
multichain-cli metar create stream KN false
multichain-cli metar create stream LC false
multichain-cli metar create stream MF false
multichain-cli metar create stream PM false
multichain-cli metar create stream VC false
multichain-cli metar create stream WS false
multichain-cli metar create stream SM false
multichain-cli metar create stream ST false
multichain-cli metar create stream SA false
multichain-cli metar create stream SN false
multichain-cli metar create stream RS false
multichain-cli metar create stream SC false
multichain-cli metar create stream SL false
multichain-cli metar create stream SG false
multichain-cli metar create stream SX false
multichain-cli metar create stream SK false
multichain-cli metar create stream SI false
multichain-cli metar create stream SB false
multichain-cli metar create stream SO false
multichain-cli metar create stream ZA false
multichain-cli metar create stream GS false
multichain-cli metar create stream SS false
multichain-cli metar create stream ES false
multichain-cli metar create stream LK false
multichain-cli metar create stream SD false
multichain-cli metar create stream SR false
multichain-cli metar create stream SJ false
multichain-cli metar create stream SZ false
multichain-cli metar create stream SE false
multichain-cli metar create stream CH false
multichain-cli metar create stream SY false
multichain-cli metar create stream TW false
multichain-cli metar create stream TJ false
multichain-cli metar create stream TZ false
multichain-cli metar create stream TH false
multichain-cli metar create stream TL false
multichain-cli metar create stream TG false
multichain-cli metar create stream TK false
multichain-cli metar create stream TO false
multichain-cli metar create stream TT false
multichain-cli metar create stream TN false
multichain-cli metar create stream TR false
multichain-cli metar create stream TM false
multichain-cli metar create stream TC false
multichain-cli metar create stream TV false
multichain-cli metar create stream UG false
multichain-cli metar create stream UA false
multichain-cli metar create stream AE false
multichain-cli metar create stream GB false
multichain-cli metar create stream US false
multichain-cli metar create stream UM false
multichain-cli metar create stream UY false
multichain-cli metar create stream UZ false
multichain-cli metar create stream VU false
multichain-cli metar create stream VE false
multichain-cli metar create stream VN false
multichain-cli metar create stream VG false
multichain-cli metar create stream VI false
multichain-cli metar create stream WF false
multichain-cli metar create stream EH false
multichain-cli metar create stream YE false
multichain-cli metar create stream ZM false
multichain-cli metar create stream ZW false

